---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Нельзя отредактировать количество товара
  - При переключении языка на русский язык часть слов не переводится
  
  
